Repository ksauraj/jee_counsellor, pull requests merged in 2024-10, with the labels that each got.

#32 added progress bar
  requirements.txt
  tool.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024

#35 Fixed Ui for html page
  assets/Xlogo.png
  assets/fork.png
  assets/github.png
  assets/linkedin.png
  assets/profile.jpg
  tool.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest-2024, hacktoberfest, hacktoberfest2024

#39 tool : fixed unwanted text in progress bar
  tool.py
Labels: approved ✅, hacktoberfest, hacktoberfest2024

#43 added 2024 csab data
  assets/Xlogo.png
  assets/fork.png
  assets/github.png
  assets/linkedin.png
  assets/profile.jpg
  csab/2024/round_1/ranks_all.csv
  csab/2024/round_1/ranks_gftis.csv
  csab/2024/round_1/ranks_iiits.csv
  csab/2024/round_1/ranks_nits.csv
  csab/2024/round_2/ranks_all.csv
  csab/2024/round_2/ranks_gftis.csv
  csab/2024/round_2/ranks_iiits.csv
  csab/2024/round_2/ranks_nits.csv
Labels: approved ✅, hacktoberfest, hacktoberfest2024, data-addition

#45 added 2024 josaa data
  josaa/2024/round_1/ranks_all.csv
  josaa/2024/round_1/ranks_gftis.csv
  josaa/2024/round_1/ranks_iiits.csv
  josaa/2024/round_1/ranks_iits.csv
  josaa/2024/round_1/ranks_nits.csv
  josaa/2024/round_2/ranks_all.csv
  josaa/2024/round_2/ranks_gftis.csv
  josaa/2024/round_2/ranks_iiits.csv
  josaa/2024/round_2/ranks_iits.csv
  josaa/2024/round_2/ranks_nits.csv
  josaa/2024/round_3/ranks_all.csv
  josaa/2024/round_3/ranks_gftis.csv
  josaa/2024/round_3/ranks_iiits.csv
  josaa/2024/round_3/ranks_iits.csv
  josaa/2024/round_3/ranks_nits.csv
  josaa/2024/round_4/ranks_all.csv
  josaa/2024/round_4/ranks_gftis.csv
  josaa/2024/round_4/ranks_iiits.csv
  josaa/2024/round_4/ranks_iits.csv
  josaa/2024/round_4/ranks_nits.csv
  josaa/2024/round_5/ranks_all.csv
  josaa/2024/round_5/ranks_gftis.csv
  josaa/2024/round_5/ranks_iiits.csv
  josaa/2024/round_5/ranks_iits.csv
  josaa/2024/round_5/ranks_nits.csv
Labels: hacktoberfest-accepted, approved ✅, hacktoberfest, hacktoberfest2024

#49 tool: implement csab 2024 all rounds in tool
  .gitignore
  csab/2024/round_1/ranks.csv
  csab/2024/round_2/ranks.csv
  tool.py
Labels: approved ✅, hacktoberfest-2024, hacktoberfest, hacktoberfest2024

#50 tool: fix unwanted ordering in generated html file
  tool.py
Labels: hacktoberfest-accepted, approved ✅, hacktoberfest, hacktoberfest2024

#51 dependencies: update requirements in requirements.txt
  requirements.txt
Labels: hacktoberfest, hacktoberfest2024

#52 tool: implement josaa 2024 all rounds in tool
  tool.py
Labels: enhancement, hacktoberfest, hacktoberfest2024

#47 feat: added clear output directory feature
  tool.py
Labels: approved ✅, hacktoberfest, hacktoberfest2024

#54 docs: use of `venv` over `--break-system-packages` while installing dependencies
  README.md
Labels: documentation, approved ✅, hacktoberfest, hacktoberfest2024
